name: X-Jlink

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
    secrets:
      gpg-passphrase:
        required: true
      oci-compartment-id:
        required: true

permissions:
  contents: read

jobs:
  jlink:
    name: Jlink
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRO }}
          cache: gradle

      - name: Version
        if: endsWith(${{ inputs.project-version }}, '-SNAPSHOT') != true
        run: |
          echo ${{ inputs.project-version }} > VERSION

      - name: Build
        run: ./gradlew -Prelease=true -PreproducibleBuild=true build -S
        env:
          JRELEASER_OCI_COMPARTMENTID: ${{ secrets.oci-compartment-id }}

      - name: Jlink
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: assemble --assembler jlink
          setup-java: false
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-jlink
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Dependencies
        run: |
          ls -l plugins/riot/build/dependencies/flat
          ls -l plugins/riot/build/dependencies/graalvm

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: artifacts
          path: |
            plugins/riot/build/libs/
            plugins/riot/build/dependencies/
            plugins/riot/build/distributions/

      - name: Stop Gradle daemon
        shell: bash
        run: ./gradlew -stop

      - name: Upload jlink
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: jlink
          path: |
            out/jreleaser/assemble/riot-standalone/jlink/*.zip
